// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

// Default mock implementation of the API callbacks

#include "mongoose_glue.h"
static struct lights s_lights = {false, false};
void glue_get_lights(struct lights *data) {
  *data = s_lights;  // Sync with your device
}
void glue_set_lights(struct lights *data) {
  s_lights = *data; // Sync with your device
}

static struct status s_status = {0, "Idle"};
void glue_get_status(struct status *data) {
  *data = s_status;  // Sync with your device
}
void glue_set_status(struct status *data) {
  s_status = *data; // Sync with your device
}

